CREATE OR REPLACE FUNCTION recalculate_all_balances()
RETURNS void AS $$
DECLARE
  prof RECORD;
  v_task_reward NUMERIC;
  v_gmail_reward NUMERIC;
  v_referral_reward NUMERIC;
  v_referred_bonus NUMERIC;
  v_withdrawal NUMERIC;
  v_total_balance NUMERIC;
  v_created TIMESTAMP WITH TIME ZONE;
BEGIN
  -- Update referrals table to make sure the amount matches what the user asked
  -- "Reffar hoiye join hole 10 tarikher por 50 taka, er age hole 15 taka"
  UPDATE referrals
  SET reward_amount = CASE 
    WHEN created_at >= '2026-06-10 00:00:00+06'::timestamp THEN 50 
    ELSE 15 
  END;

  FOR prof IN SELECT user_id FROM user_profiles LOOP
    
    -- 1. Approved Tasks
    SELECT COALESCE(SUM(t.reward), 0) INTO v_task_reward
    FROM submissions s
    JOIN tasks t ON s.task_id = t.id
    WHERE s.user_id = prof.user_id AND s.status = 'approved' AND t.task_type != 'gmail';

    -- 2. Approved Gmail Tasks
    SELECT COALESCE(SUM(reward), 0) INTO v_gmail_reward
    FROM gmail_tasks
    WHERE locked_by = prof.user_id AND status = 'approved';

    -- 3. Referrals generated by this user (referrer_id)
    SELECT COALESCE(SUM(reward_amount), 0) INTO v_referral_reward
    FROM referrals
    WHERE referrer_id = prof.user_id;

    -- 4. Did they join via referral themselves?
    SELECT COALESCE(SUM(50), 0) INTO v_referred_bonus
    FROM referrals 
    WHERE referred_user_id = prof.user_id;

    -- 5. Withdrawals (pending or approved/completed)
    SELECT COALESCE(SUM(amount), 0) INTO v_withdrawal
    FROM withdrawals
    WHERE user_id = prof.user_id AND status NOT LIKE 'rejected%';

    -- "extra 50 taka ad korar jonno sql dau" -> adding a flat 50 to everyone
    v_total_balance := v_task_reward + v_gmail_reward + v_referral_reward + v_referred_bonus - v_withdrawal + 50;
    
    IF v_total_balance < 0 THEN v_total_balance := 0; END IF;

    UPDATE user_profiles
    SET balance = v_total_balance
    WHERE user_id = prof.user_id;

    -- Update legacy JSON as well
    UPDATE auth.users
    SET raw_user_meta_data = jsonb_set(
      COALESCE(raw_user_meta_data, '{}'::jsonb),
      '{balance}',
      to_jsonb(v_total_balance)
    )
    WHERE id = prof.user_id;

  END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
